add initial electra spec
ethereum/builder-specs pull request #101
Opened 2024-05-01 20:40 UTC by jacobkaufmann

add initial `electra` spec.

2024-05-07 13:58 UTC, ralexstokes approved these changes
looks good! may hold off on merging until after the first iteration of pectra following devnet-0

2024-05-15 14:00 UTC, terencechain approved these changes

2024-09-17 19:49 UTC, ralexstokes requested changes
looks good!

we are blocked on the `beacon-apis` but this should be good enough to get implementer's started

2024-09-17 19:49 UTC, ralexstokes commented on specs/electra/builder.md
> +
add note about "this replaces the `ExecutionPayloadAndBlobsBundle`

2024-09-17 19:49 UTC, ralexstokes commented on specs/electra/builder.md
> +
another line of text: "spec works like it did in previous forks, with changes to types as given below"

2024-09-18 11:12 UTC, nflaig commented on specs/electra/builder.md
> +    execution_requests: ExecutionRequests
No longer the case since https://github.com/ethereum/consensus-specs/pull/3875

2024-09-18 11:31 UTC, rkrasiuk commented on specs/electra/builder.md
> +    execution_requests: ExecutionRequests
is anybody working on updating `execution-apis`?

2024-09-18 20:33 UTC, ralexstokes approved these changes
updates lgtm, thanks!

2024-09-19 02:41 UTC, lucassaldanha approved these changes

2024-09-21 03:57 UTC, lucassaldanha commented on specs/electra/builder.md
> +    execution_requests: ExecutionRequests
Yes. Here is the WIP: https://github.com/ethereum/execution-apis/pull/587

2024-09-21 03:58 UTC, lucassaldanha commented on specs/electra/builder.md
> +    execution_requests: ExecutionRequests
Oh just noticed that you did it... 👍 
Nevermind :)

2024-09-22 23:03 UTC, lucassaldanha commented on specs/electra/builder.md
> +    execution_requests_root: Root # [New in Electra]
Unless I am missing something, the CL won't be able to validate the block if we don't have the actual `ExecutionRequests` in the `BuilderBid`. Instead of the `execution_requests_root`, we want the actual `execution_requests` here.

2024-09-22 23:44 UTC, potuz commented on specs/electra/builder.md
> +    execution_requests_root: Root # [New in Electra]
Interestingly enough, the root is enough in the blinded block part when the message returns to the relay, so at least there' no need for a double trip of the full requests.

2024-09-23 08:07 UTC, mkalinin commented on specs/electra/builder.md
> +    execution_requests_root: Root # [New in Electra]
@potuz do you mean they have to be in the `BuilderBid` but not necessarily in the `SignedBlindedBeaconBlock`?

2024-09-24 16:30 UTC, jacobkaufmann commented on specs/electra/builder.md
> +    execution_requests_root: Root # [New in Electra]
we have the root of the execution requests in the `BuilderBid` because those are observable, and there are concerns about MEV leakage if the execution requests are not hidden.

it is okay to only have the root of the execution requests in the `BuilderBid`, because the proposer can construct the `SignedBlindedBeaconBlock` with only the root.

once the relay receives and verifies the `SignedBlindedBeaconBlock`, it can broadcast the `SignedBeaconBlock`, revealing both the execution payload and the execution requests.

2024-09-24 16:43 UTC, terencechain commented on specs/electra/builder.md
> +    execution_requests_root: Root # [New in Electra]
`BlindedBeaconBlockBody` needs to contain `excution_requests` instead of `excution_requests_root`
Proposer needs the full execution requests, or else it can not calculate the beacon state root to sign over

2024-09-24 17:01 UTC, jacobkaufmann commented on specs/electra/builder.md
> +    execution_requests_root: Root # [New in Electra]
I see. we will need to refactor. good callout @terencechain!

2024-09-24 21:59 UTC, lucassaldanha approved these changes
LGMT

2024-09-26 16:30 UTC, terencechain commented on specs/electra/builder.md
> +    execution_requests: ExecutionRequests
I dont think you need `execution_requests` here. `execution_requests` is already part of `BuilderBid`

2024-09-26 23:10 UTC, ensi321 commented on specs/electra/builder.md
> +    execution_requests: ExecutionRequests
> I dont think you need `execution_requests` here. `execution_requests` is already part of `BuilderBid`

In this case we don't need `ExecutionBundle` at all, just keep `ExecutionPayloadAndBlobsBundle`

2024-09-27 08:13 UTC, nflaig approved these changes

2024-09-27 08:19 UTC, mkalinin commented on specs/electra/builder.md
> +    execution_requests: ExecutionRequests # [New in Electra]
Should this field type be switched to `bytes` If https://github.com/ethereum/execution-apis/pull/591 is accepted?

2024-09-28 05:48 UTC, lucassaldanha commented on specs/electra/builder.md
> +    execution_requests: ExecutionRequests # [New in Electra]
I think it makes sense to keep them consistent. So it makes sense to change it. Otherwise we need two decoding implementations on the CL side.

2024-10-08 14:16 UTC, ralexstokes commented on specs/electra/builder.md
> +    execution_requests: ExecutionRequests # [New in Electra]
I think I would leave this as-is in the spec

can mirror the Engine API for the Builder API HTTP definition

2024-10-08 23:03 UTC, ensi321 approved these changes

2024-10-09 21:19 UTC, ralexstokes commented on specs/electra/builder.md
> +    execution_requests: ExecutionRequests # [New in Electra]
to @lucassaldanha point, given that this version will be in the `beacon-apis`, I don't think we are making an additional ask of CLs to deal with this version here

will go ahead and merge this for now to unblock devnet-4, if we decide we want to mirror the Engine API we can address in a future PR

2024-10-09 21:23 UTC, merged

2024-10-10 15:10 UTC, nflaig commented on specs/electra/builder.md
> +    execution_requests: ExecutionRequests # [New in Electra]
> Should this field type be switched to bytes

What would be the difference of this compared to using SSZ encoding for the whole `BuilderBid`? It seems much cleaner to have the option to use JSON (for debugging purposes) or SSZ in transit and is what we do on the beacon-api for most of the time sensitive apis.

If we are concerned about latency, should move to using SSZ on the builder api as proposed in https://github.com/ethereum/builder-specs/pull/104

2024-10-10 17:26 UTC, ralexstokes commented on specs/electra/builder.md
> +    execution_requests: ExecutionRequests # [New in Electra]
yeah I think that's a nice resolution here! and honestly likely how we should be thinking about it in the Engine API but full SSZ there will take more time

2024-10-10 17:34 UTC, nflaig commented on specs/electra/builder.md
> +    execution_requests: ExecutionRequests # [New in Electra]
> but full SSZ there will take more time

yeah I see why this is done on the engine api, but please not on CL side, embedding ssz inside json data is just the worst of both worlds, it's harder to debug issues during development and you still send json around for all others fields + it does not allow streaming the response. Ideally, we only wanna use json for development and stuff like kurtosis testing.