clarify signing for builder messages
ethereum/builder-specs pull request #15
Opened 2022-05-16 17:45 UTC by ralexstokes

fixes #14.

2022-05-16 17:57 UTC, mcdee commented on specs/README.md
> +| `DOMAIN_APPLICATION_BUILDER` | `DomainType('0x00000000')` |
I strongly recommend that there is something set here, otherwise the domain will equal the mask and that seems a potential security risk.

Also, to date the domain types have generally been specific to operations so may make sense to make this more focused than just "builder".

2022-05-16 17:57 UTC, mcdee commented on specs/README.md
> +    domain_type = DomainType(DOMAIN_APPLICATION_MASK & DOMAIN_APPLICATION_BUILDER)
If I'm reading this correctly it ends up with a domain type of 0.  Should this be `|` rather than `&`?

2022-05-16 18:07 UTC, ralexstokes commented on specs/README.md
> +| `DOMAIN_APPLICATION_BUILDER` | `DomainType('0x00000000')` |
the idea is to "index" applications which we can just start counting from 0, 1, 2, ...

but I'd be fine if we go with `0x01` to avoid the degenerate case

2022-05-16 18:08 UTC, ralexstokes commented on specs/README.md
> +| `DOMAIN_APPLICATION_BUILDER` | `DomainType('0x00000000')` |
> Also, to date the domain types have generally been specific to operations so may make sense to make this more focused than just "builder".

do you have a suggestion? not attached to this name

2022-05-16 18:09 UTC, ralexstokes commented on specs/README.md
> +    domain_type = DomainType(DOMAIN_APPLICATION_MASK & DOMAIN_APPLICATION_BUILDER)
yes sorry, thanks, I'll update

2022-05-16 18:17 UTC, mcdee commented on specs/README.md
> +| `DOMAIN_APPLICATION_BUILDER` | `DomainType('0x00000000')` |
Domains have previously been quite specific, _e.g._ `DOMAIN_DEPOSIT` and `DOMAIN_VOLUNTARY_EXIT`, so perhaps `DOMAIN_BUILDER_REGISTRATION` and `DOMAIN_BUILDER_BLOCK` or similar.

2022-05-16 18:43 UTC, ralexstokes commented on specs/README.md
> +| `DOMAIN_APPLICATION_BUILDER` | `DomainType('0x00000000')` |
yeah we could have two:

`DOMAIN_BUILDER_REGISTRATION`
`DOMAIN_BUILDER_BID`

2022-05-17 18:38 UTC, lightclient commented on specs/README.md
> +| `DOMAIN_APPLICATION_BUILDER` | `DomainType('0x00000000')` |
I'm a little worried about setting the precedent that if you are an application that needs a domain type, you need a domain type for _each_ of your operations.

2022-05-17 18:46 UTC, lightclient requested changes
I feel like we either need to better define an "application index in the application mask space" or `DOMAIN_APPLICATION_BUILDER` should just be `0x00000001`. Right now it seems to be claiming `0x00000000` is the `DomainType` for the builder, but then in `compute_builder_domain` it actually bitwise-ors it with `DOMAIN_APPLICATION_MASK`.

2022-05-17 18:46 UTC, lightclient commented on specs/README.md
> +| `DOMAIN_APPLICATION_BUILDER` | `DomainType('0x00000000')` |
This also feels wrong -- `DOMAIN_APPLICATION_BUILDER` is actually not the `DomainType` for the application (contrary to the heading), but rather the index of the application in the `DOMAIN_APPLICATION_MASK` space.

2022-05-17 21:15 UTC, realbigsean commented on specs/README.md
> +| `DOMAIN_APPLICATION_BUILDER` | `DomainType('0x00000000')` |
You need domain separation per thing you're signing so a signature for one object can't be interpreted as a valid signature for another object.

2022-05-18 14:04 UTC, mcdee commented on specs/README.md
> +| `DOMAIN_APPLICATION_BUILDER` | `DomainType('0x00000000')` |
What do you mean by "subdomain" here?

2022-05-18 17:35 UTC, ralexstokes commented
ok I've update the PR to a "lowest common denominator"

I think the only other decision we should make here is if we change the domain so there is less risk of misuse/collisions/ etc.

If we don't like the `DOMAIN_APPLICATION_BUILDER` as defined then I'd suggest this:

`DomainType(0xdd70c7b1)`

this value is the first four bytes of the hash of the python term `b"ethereum-mev-builder"` with the top bit set.

we should separately consider adding versioning to the builder bids but if there is support to merge this, we can cut a release and give everyone something stable to start testing on kiln

2022-05-19 14:57 UTC, realbigsean commented
I actually think `DOMAIN_APPLICATION_BUILDER` needs to be spec'd in terms of the bit mask because it's configurable in the consensus spec and if it changes, this breaks

2022-05-19 16:35 UTC, ralexstokes commented
@realbigsean 


>  it's configurable in the consensus spec and if it changes, this breaks

it shouldn't change tho -- from the spec:

> The following values are (non-configurable) constants used throughout the specification.

we can be explicit about the bit mask but it seems to be causing some confusion; in lieu of taking more time to sort that out I was going to just assert there is some `DomainType` -- it has some extra semantics wrt the consensus spec but the builder specs here don't care about that

2022-05-19 16:49 UTC, realbigsean commented
> @realbigsean
> 
> > it's configurable in the consensus spec and if it changes, this breaks
> 
> it shouldn't change tho -- from the spec:
> 
> > The following values are (non-configurable) constants used throughout the specification.

Ah true, this is good with me then.

2022-05-19 23:29 UTC, lightclient commented on specs/README.md
> +| `DOMAIN_APPLICATION_BUILDER` | `DomainType('0x00000000')` |
@mcdee an application could define a wrapper for `compute_signing_root` like this:

```python
def compute_app_signing_root(ssz_object: SSZObject, subdomain: Domain) -> Root:
    return eth2spec.mainnet.spec.compute_signing_root(SigningData(
        object_root=hash_tree_root(ssz_object)
        domain=subdomain,
    ), compute_domain(DOMAIN_TYPE_APPLICATION_XYZ))
``` 

This way, the outer object is in the domain of the application and the inner object has an application-specific subdomain.

2022-05-19 23:31 UTC, merged