[wip] Builder spec changes for Capella & EIP-4844
ethereum/builder-specs pull request #58
Opened 2022-12-01 14:31 UTC by jimmygchen

## Description

- Updated `ExecutionPayload` & `BeaconBlockBody`  types to align with Capella & EIP-4844 specs. (Depends on types from this Beacon API PR: https://github.com/ethereum/beacon-APIs/pull/271)
- Add `blob_kzg_commitments` to `getExecutionPayloadHeader` response (`SignedBuilderBid`), so that validator can include it in the block and create a signature over the blinded block.
- A new `submitBlindedBlockV2` endpoint, that includes `blobs_sidecar` in the response (`SignedBeaconBlockAndBlobsSidecar`).

TODO: there are some more clean ups required, but would be great to get some feedback on this! 🙏 

## Changes for EIP-4844

```mermaid
sequenceDiagram
    participant validator
    participant consensus
    participant mev_boost
    Title: Block Proposal with Builder API (EIP-4844)
    validator->>consensus: GET v2/validator/blinded_blocks/{slot}
    consensus->>mev_boost: GET v1/builder/header/{slot}/{parent_hash}/{pubkey}
    mev_boost-->>consensus: GET v1/builder/header/{slot}/{parent_hash}/{pubkey} response
    Note left of mev_boost: add `blob_kzg_commitments` to response (`SignedBuilderBid`)
    consensus-->>validator: GET v2/validator/blinded_blocks/{slot} response
    Note left of consensus: add `blob_kzg_commitments` to response
    Note over validator: include `blob_kzg_commitments` in block and sign the header
    validator->>consensus: POST beacon/blinded_blocks
    consensus->>mev_boost: POST /eth/v2/builder/blinded_blocks
    mev_boost-->>consensus: POST /eth/v2/builder/blinded_blocks response
    Note left of mev_boost: revealed payload will have to include `blobs_sidecar` and kzg proof
    Note over consensus: construct block and broadcast block
```

2022-12-01 14:38 UTC, jimmygchen commented on apis/builder/blinded_blocks.yaml
> +            $ref: "../../builder-oapi.yaml#/components/examples/Eip4844.SignedBlindedBeaconBlock"
Not sure if we should support eip-4844 version  for the v1 API if we plan to use `submitBlindedBlockV2`?

2022-12-02 06:47 UTC, 0xGabi requested changes
Great work on adding the `blobs_sidecar`, I believe we are getting close to mark the PR ready for review.

I had some general thoughts about writing the spec:

- While looking through the [`execution-apis` spec](https://github.com/ethereum/execution-apis/blob/main/src/engine/specification.md) I start wondering if we want to further clarify the changes between `submitBlindedBlockV1` and `submitBlindedBlockV2`.

- If we follow the same [versioning criteria](https://github.com/ethereum/execution-apis/blob/main/src/engine/specification.md#versioning) of the execution API. We may need to version the structures (i.e. `SignedBuilderBidV2`) and as a consequence have a `getHeaderV2`. I'm not sure we want to follow that path but wanted to bring it for discussion.

2022-12-02 06:47 UTC, 0xGabi commented on apis/builder/blinded_blocks.yaml
> +            $ref: "../../builder-oapi.yaml#/components/examples/Eip4844.SignedBlindedBeaconBlock"
That's a good point. Looking the [versioning section of the `execution-apis`](https://github.com/ethereum/execution-apis/blob/main/src/engine/specification.md#versioning) my understanding is that we should treat each version as independent. I vote for removing 4844 on v1.

2022-12-02 06:47 UTC, 0xGabi commented on types/eip4844/block_and_blobs_sidecar.yaml
> +Eip4844:
I'm not convinced of having this types definitions on the builder spec. I think we should move them to the [`beacon-apis`](https://github.com/ethereum/beacon-APIs) repo. I see this types definitions being useful to more dependencies of the `beacon-apis`.

2022-12-02 06:47 UTC, 0xGabi commented on apis/builder/blinded_blocks.yaml
> +            $ref: "../../builder-oapi.yaml#/components/examples/Eip4844.SignedBlindedBeaconBlock"
What do you think of including Capella as part of the `submitBlindedBlockV2`? And remove Capella form v1 as well.

2022-12-02 07:02 UTC, jimmygchen commented
> What do you think of including Capella as part of the submitBlindedBlockV2? And remove Capella form v1 as well.
I'm not sure if we want to include submitBlindedBlockV2 in V2 since it's not strictly required for Capella, and I think we'd need to be able to ship withdrawals / Capella if 4844 doesn't get implemented in time.

2022-12-02 07:05 UTC, jimmygchen commented on types/eip4844/block_and_blobs_sidecar.yaml
> +Eip4844:
There's currently no dependencies in Beacon API, so adding it there means we'd end up having unused schema in the repo and could get accidentally deleted. I'm all for moving it there if it's required in the Beacon API.

2022-12-02 07:06 UTC, jimmygchen commented on .gitmodules
> +	url = git@github.com:jimmygchen/beacon-APIs.git
Done

2022-12-02 07:10 UTC, jimmygchen commented on apis/builder/blinded_blocks.yaml
> +            $ref: "../../builder-oapi.yaml#/components/examples/Eip4844.SignedBlindedBeaconBlock"
> That's a good point. Looking the [versioning section of the `execution-apis`](https://github.com/ethereum/execution-apis/blob/main/src/engine/specification.md#versioning) my understanding is that we should treat each version as independent. I vote for removing 4844 on v1.

I kept the 4844 here because we haven't really discussed about deprecating this, and making it a requirement for clients to use V2. I think it would be great to get some feedback from client teams on this.

> What do you think of including Capella as part of the submitBlindedBlockV2? And remove Capella form v1 as well

I'm not sure if we want to include submitBlindedBlockV2 in V2 since it's not strictly required for Capella, and I think we'd need to be able to ship withdrawals / Capella if 4844 doesn't get implemented in time.

2022-12-02 07:31 UTC, jimmygchen commented
> * While looking through the [`execution-apis` spec](https://github.com/ethereum/execution-apis/blob/main/src/engine/specification.md) I start wondering if we want to further clarify the changes between `submitBlindedBlockV1` and `submitBlindedBlockV2`.
> * If we follow the same [versioning criteria](https://github.com/ethereum/execution-apis/blob/main/src/engine/specification.md#versioning) of the execution API. We may need to version the structures (i.e. `SignedBuilderBidV2`) and as a consequence have a `getHeaderV2`. I'm not sure we want to follow that path but wanted to bring it for discussion.

Great point, I'm not sure tbh, and I'd like to hear some more discussions on this too. There were some discussions on discord earlier, and it looks like we don't need a new version just for new fields, however in this case we're changing the endpoint to return a  `SignedBeaconBlockAndSidecar` instead of `ExecutionPayload`, so it's a breaking change.
https://discord.com/channels/595666850260713488/1031999860997619843/1038023245900820531

2022-12-02 07:38 UTC, jimmygchen commented on apis/builder/header.yaml
> +              $ref: "../../builder-oapi.yaml#/components/examples/Eip4844.SignedBuilderBid"
I'm having some issues with lint here complaining about these examples matching multiple schemas, and not sure what's the best way to resolve this.

I think the json examples are matching multiple schemas because the schema allows for additional properties. I think we could set `additionalProperties` to `false` so that it doesn't match all, but I haven't seen this approach used anywhere else in the API repos.

```
~/builder-specs/examples/bellatrix/signed_builder_bid.json
 4:13  error  oas3-valid-media-example  "data" property must match exactly one schema in oneOf  value.data

~/builder-specs/examples/capella/signed_builder_bid.json
 4:13  error  oas3-valid-media-example  "data" property must match exactly one schema in oneOf  value.data

~/builder-specs/examples/eip4844/signed_builder_bid.json
 4:13  error  oas3-valid-media-example  "data" property must match exactly one schema in oneOf  value.data
```

2022-12-02 10:23 UTC, metachris commented on apis/builder/blinded_blocks_v2.yaml
> +post:
from the discussions i've had, there seems to be a preference for reusing the existing API call, rather than introducing a new V2 one.

2022-12-02 14:29 UTC, jimmygchen commented on apis/builder/blinded_blocks_v2.yaml
> +post:
Hey thanks for the insight @metachris. I've seen some discussion on discord earlier too. My understanding was that the version header is used for determining the payload structure, so clients should be able to parse the same payload type from different forks. It make sense to me to keep the same API if the response type is the same, i.e. if we return `Eip4844.ExeuctionPayload`.

However I think we'd also want to include blobs and the kzg proof, so it would be more convenient to change the response type to `SignedBeaconBlockAndBlobsSidecar` (with the revealed `ExecutionPayload` wrapped within the block), and the clients can just broadcast the block after receiving it, rather than having to retrieve the sidecar and construct the beacon block. Does this make sense? I haven't seen an API allowing a completely different response type, so I thought we may want to increment the version, but keen to hear your thoughts! 

(cc: @ajsutton)

2022-12-02 15:35 UTC, metachris commented
Just wanted to say thanks for the contribution! 🚀  
Would love to understand more about where this is coming from.

pinging @lightclient @jtraglia @lightclient @terencechain @tbenr @ajsutton (and others) for review and feedback

2022-12-02 15:56 UTC, jimmygchen commented on apis/builder/header.yaml
> +              $ref: "../../builder-oapi.yaml#/components/examples/Eip4844.SignedBuilderBid"
I don't see any easy way around without adding `required` for new properties everywhere, which is a bit ugly, so I went with using `anyOf` instead - if anyone has a better solution for this please let me know!

2022-12-12 15:02 UTC, tbenr commented
Regarding submitBlindedBlock, It makes sense to me to have a V2 returning the entire`SignedBeaconBlockAndBlobsSidecar`. It reduces complexity and the overhead is minimal since `ExecutionPayload` and `BlobsSidecar` are the biggest objects we need to get anyway.

2022-12-13 21:20 UTC, ralexstokes requested changes
excellent work!

I left some questions and feedback -- this is a great start :)

This PR is fine as is but something to keep in mind for the future is that it is much easier to review smaller PRs, so this one could easily be a PR just for capella changes and then a separate one for 4844 changes

2022-12-13 21:20 UTC, ralexstokes commented on types/capella/bid.yaml
> +        description: "BLS public key of builder."
I think we can define a `BuilderBidCommon` schema to reduce the repetition here

2022-12-13 21:20 UTC, ralexstokes commented on examples/capella/execution_payload.json
> +      ]
ideally we have an actual hex-encoded withdrawal here

2022-12-13 21:20 UTC, ralexstokes commented on examples/eip4844/execution_payload.json
> +        "0x02f878831469668303f51d843b9ac9f9843b9aca0082520894c93269b73096998db66be0441e836d873535cb9c8894a19041886f000080c001a031cc29234036afbf9a1fb9476b463367cb1f957ac0b919b69bbc798436e604aaa018c4e9
same on withdrawal example here

2022-12-13 21:20 UTC, ralexstokes commented on types/eip4844/block_and_blobs_sidecar.yaml
> +    description: "A blob is `FIELD_ELEMENTS_PER_BLOB * size_of(BLSFieldElement) = 4096 * 32 = 131072` bytes (`DATA`) representing a SSZ-encoded Blob as defined in EIP-4844"
what do you think about moving `SignedBeaconBlockAndBlobsSidecar` to the `beacon-apis` and then just referencing them here?

2022-12-13 21:20 UTC, ralexstokes commented on apis/builder/header.yaml
> +                anyOf:
not sure on the semantics of `oneOf` vs `anyOf` but it sounds like we want `oneOf` here

2022-12-13 21:20 UTC, ralexstokes commented on apis/builder/blinded_blocks_v2.yaml
> +post:
> I haven't seen an API allowing a completely different response type

this should be fine -- we should be able to just add the right type to the v1 endpoint

let's drop v2 here and extend v1 to also support a new type that contains the `ExecutionPayload` and the `BlobsSidecar`, calling it something like `ExecutionPayloadWithBlobsSidecar`

2022-12-14 21:54 UTC, jimmygchen commented on apis/builder/header.yaml
> +                anyOf:
Yes, it should be `oneOf`, I had a bit of issues getting this to work earlier (noted in [this comment](https://github.com/ethereum/builder-specs/pull/58/files/ea928bf1b8db6221bf729b935a889b890cff279c#r1037860896)) - perhaps we'll need to make all new properties in schema versions `required` in order for the examples pass validation::

> I'm having some issues with lint here complaining about these examples matching multiple schemas, and not sure what's the best way to resolve this.
> I think the json examples are matching multiple schemas because the schema allows for additional properties. I think we could set `additionalProperties` to `false` so that it doesn't match all, but I haven't seen this approach used anywhere else in the API repos.

```
~/builder-specs/examples/bellatrix/signed_builder_bid.json
 4:13  error  oas3-valid-media-example  "data" property must match exactly one schema in oneOf  value.data

~/builder-specs/examples/capella/signed_builder_bid.json
 4:13  error  oas3-valid-media-example  "data" property must match exactly one schema in oneOf  value.data

~/builder-specs/examples/eip4844/signed_builder_bid.json
 4:13  error  oas3-valid-media-example  "data" property must match exactly one schema in oneOf  value.data
```

> I don't see any easy way around without adding required for new properties everywhere, which is a bit ugly, so I went with using anyOf instead - if anyone has a better solution for this please let me know!

2022-12-14 21:57 UTC, jimmygchen commented on .gitmodules
> +	url = git@github.com:jimmygchen/beacon-APIs.git
done

2022-12-14 22:09 UTC, jimmygchen commented on types/eip4844/block_and_blobs_sidecar.yaml
> +    description: "A blob is `FIELD_ELEMENTS_PER_BLOB * size_of(BLSFieldElement) = 4096 * 32 = 131072` bytes (`DATA`) representing a SSZ-encoded Blob as defined in EIP-4844"
@0xGabi made a comment about this [here](https://github.com/ethereum/builder-specs/pull/58#discussion_r1037828181) as well - I wasn't sure about this as it's not used in `beacon-apis` (and may lead to validation warnings if there's one), but happy to move this since we've got more arguments for moving over to `beacon-apis`

2022-12-15 07:43 UTC, jimmygchen commented on apis/builder/blinded_blocks.yaml
> +            $ref: "../../builder-oapi.yaml#/components/examples/Eip4844.SignedBlindedBeaconBlock"
we can close this now, given we're not going ahead with V2

2022-12-15 08:44 UTC, jimmygchen commented on apis/builder/header.yaml
> +                anyOf:
Changed to `oneOf`. Got this working by adding `additioanlProperties: false` to `ExecutionPayloadHeader` and `BuilderBid` types.

2022-12-15 08:46 UTC, jimmygchen commented on types/eip4844/block_and_blobs_sidecar.yaml
> +    description: "A blob is `FIELD_ELEMENTS_PER_BLOB * size_of(BLSFieldElement) = 4096 * 32 = 131072` bytes (`DATA`) representing a SSZ-encoded Blob as defined in EIP-4844"
Done.

2022-12-15 12:37 UTC, jimmygchen commented on types/eip4844/block_and_blobs_sidecar.yaml
> +Eip4844:
moved to beacon APIs

2022-12-15 13:29 UTC, jimmygchen commented on apis/builder/blinded_blocks_v2.yaml
> +post:
Done, thanks!

2022-12-15 21:46 UTC, 0xGabi approved these changes
Well done. I like `ExecutionPayloadAndBlobSidecar`.

2022-12-15 21:46 UTC, 0xGabi commented on .gitmodules
> +	# update to ethereum repo once PR is merged: https://github.com/ethereum/beacon-APIs/pull/271
```suggestion
```

2022-12-16 03:13 UTC, jimmygchen commented on types/capella/bid.yaml
> +        description: "BLS public key of builder."
Done, thanks

2022-12-16 03:41 UTC, jimmygchen commented on examples/capella/execution_payload.json
> +      ]
ah nice catch, updated now - just realised `withdrawals` is a list of objects.. wonder why validation didn't pick up 🤔

2022-12-16 03:41 UTC, jimmygchen commented on examples/eip4844/execution_payload.json
> +        "0x02f878831469668303f51d843b9ac9f9843b9aca0082520894c93269b73096998db66be0441e836d873535cb9c8894a19041886f000080c001a031cc29234036afbf9a1fb9476b463367cb1f957ac0b919b69bbc798436e604aaa018c4e9
Done

2022-12-16 03:42 UTC, jimmygchen commented
Thanks for the review @ralexstokes @0xGabi! 🙏  I've addressed your comments, please review again.

2022-12-16 06:16 UTC, 0xGabi approved these changes
LGTM

2022-12-16 06:16 UTC, 0xGabi commented on examples/capella/execution_payload.json
> +        {
👍

2022-12-23 09:35 UTC, metachris commented
I think it would make sense to split this PR into two -- one for Capella changes, and another one for EIP4844 changes? (The 4844 PR could point to the Capella PR to reuse anything that's already in there)

2023-01-02 15:44 UTC, g11tech commented on examples/eip4844/signed_beacon_block_and_blobs_sidecar.json
> +              "0x02f878831469668303f51d843b9ac9f9843b9aca0082520894c93269b73096998db66be0441e836d873535cb9c8894a19041886f000080c001a031cc29234036afbf9a1fb9476b463367cb1f957ac0b919b69bbc798436e604aaa0
withdrawals json here looks incorrect

2023-01-03 00:21 UTC, jimmygchen commented on examples/eip4844/signed_beacon_block_and_blobs_sidecar.json
> +              "0x02f878831469668303f51d843b9ac9f9843b9aca0082520894c93269b73096998db66be0441e836d873535cb9c8894a19041886f000080c001a031cc29234036afbf9a1fb9476b463367cb1f957ac0b919b69bbc798436e604aaa0
Thanks @g11tech that's fixed now!

2023-01-03 00:42 UTC, jimmygchen commented
> I think it would make sense to split this PR into two -- one for Capella changes, and another one for EIP4844 changes? (The 4844 PR could point to the Capella PR to reuse anything that's already in there)

Hi @metachris @ralexstokes I've just done that now, please see the two separated PRs
- Capella #60 
- EIP-4844 #61 

Closing this PR.

2023-01-03 00:42 UTC, closed without merging